# Generated by Django 5.2.1 on 2025-05-24 23:11

import fernet_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_chat_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=fernet_fields.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=fernet_fields.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=fernet_fields.fields.EncryptedCharField(blank=True, max_length=20, null=True),
        ),
    ]
