"""
Django settings for messenger_project project.

Generated by 'django-admin startproject' using Django 5.1.7.
"""
import django.utils.encoding as _enc
_enc.force_text = _enc.force_str

import os
import environ
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent


env = environ.Env(
    DEBUG=(bool, False),
    FERNET_KEYS=(list, [])
)

env_file = BASE_DIR / ".env"
if env_file.exists():
    env.read_env(env_file)   # <-- именно так, через экземпляр

# 3) Теперь все переменные из .env в env доступны
SECRET_KEY = env('SECRET_KEY', default='django-insecure-6ima9kjnf@_tkh$_4-+$j7**q+cb$rt5rr($x8tc3*-da+5e2r')  # пример
DEBUG      = env('DEBUG')
ALLOWED_HOSTS = ['127.0.0.1', 'localhost']

DOWNLOAD_TOKEN_KEY = env('DOWNLOAD_TOKEN_KEY', default=None)
FERNET_KEYS = env.list('FERNET_KEYS')

# SECRET_KEY = 'django-insecure-6ima9kjnf@_tkh$_4-+$j7**q+cb$rt5rr($x8tc3*-da+5e2r'
# DEBUG = True
# ALLOWED_HOSTS = []

INSTALLED_APPS = [
    'corsheaders',                     # 1) corsheaders в самом начале
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core.apps.CoreConfig',
    'rest_framework',
    'channels',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

MIDDLEWARE = [
    # 2) CORS Middleware должен идти самым первым,
    #    раньше CommonMiddleware и SecurityMiddleware:
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',

    # Остальные ниже
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'messenger_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'messenger_project.wsgi.application'
ASGI_APPLICATION = 'messenger_project.asgi.application'

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get("DB_NAME", "messenger"),
        "USER": os.environ.get("DB_USER", "postgres"),
        "PASSWORD": os.environ.get("DB_PASSWORD", ""),
        "HOST": os.environ.get("DB_HOST", "localhost"),
        "PORT": os.environ.get("DB_PORT", "5432"),
    }
}

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

STATIC_URL = 'static/'
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_ROOT = BASE_DIR / 'media'
MEDIA_URL = '/media/'

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
    },
}

# Включаем CORS для всех доменов (для отладки)
CORS_ALLOW_ALL_ORIGINS = True

# Если потом захотите ограничить конкретными доменами:
# CORS_ALLOWED_ORIGINS = [
#     "http://localhost:3000",
#     "http://127.0.0.1:3000",
# ]

FILE_UPLOAD_MAX_MEMORY_SIZE = 20 * 1024 * 1024
DATA_UPLOAD_MAX_MEMORY_SIZE = 20 * 1024 * 1024

BACKEND_URL = env('BACKEND_URL', default='http://127.0.0.1:8000')
DEFAULT_FILE_STORAGE = 'core.storage.EncryptedFileSystemStorage'